server:
  port: 8181

logging:
  level:
    root: debug

spring:
  datasource:
    url: jdbc:mysql://19341.synology.me:3306/yiisun?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jwlee
    password: Epsltm1124!

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

smtp:
  mail:
    host: mail.19341.synology.me
    port: 25
    id: 19341
    password: 108108Jo
    sender.address: 19341@daworld.synology.me

mybatis:
  type-handlers-package: com.model.common.util.mybatis
  configuration:
    map-underscore-to-camel-case: true